// ─────────────────────────────────────────────────────────────────────────────
// Single source of truth: src/client/overlay.css + src/client/overlay-host.css
// overlay-css.gen.ts is auto-generated by scripts/gen-overlay-css.mjs (prebuild).
// Both the Shadow DOM bundle (via this module) and the showcase HTML (via <link>)
// reference the same CSS files, so they are always 1-1 in design.
// ─────────────────────────────────────────────────────────────────────────────
export { OVERLAY_CSS, HOST_PAGE_CSS } from "../overlay-css.gen.js";
