import { defineConfig } from "tsup";
import {
  cpSync,
  existsSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";

export default defineConfig([
  // Browser overlay bundle (built first — generates overlay-bundle.gen.ts for CLI)
  {
    entry: { "overlay-browser": "src/client/overlay-browser/index.ts" },
    format: ["iife"],
    target: "chrome90",
    platform: "browser",
    outDir: "dist/client",
    clean: false,
    sourcemap: false,
    minifyWhitespace: true,
    minifySyntax: true,
    minifyIdentifiers: false,
    noExternal: [/.*/],
    esbuildOptions(options) {
      // JSX support needed for React overlay components imported from overlay-react/
      options.define = { "process.env.NODE_ENV": '"production"' };
      options.outExtension = { ".js": ".js" };
    },
    onSuccess: async () => {
      const bundle = readFileSync("dist/client/overlay-browser.js", "utf-8");
      const bundleExport = `// AUTO-GENERATED — run 'npm run build' to regenerate. Do not edit manually.\nexport const OVERLAY_BROWSER_BUNDLE = ${JSON.stringify(bundle)};\n`;
      writeFileSync("src/client/overlay-bundle.gen.ts", bundleExport);
      // Also write to packages/shared so the SaaS can import it at build time.
      writeFileSync("../../packages/shared/src/overlay-bundle.gen.ts", bundleExport);
      // Copy the single-source CSS files so external tools (showcase, devtools) can link them directly
      cpSync("src/client/overlay.css", "dist/overlay.css");
      cpSync("src/client/overlay-host.css", "dist/overlay-host.css");
      // Remove stale CSS/global artifacts from the dist/client dir (clean: false is needed for multi-target)
      for (const stale of ["dist/client/overlay-browser.css", "dist/client/overlay-browser.global.js"]) {
        if (existsSync(stale)) rmSync(stale);
      }
      console.log("[tsup] Generated src/client/overlay-bundle.gen.ts");
    },
  },
  // Kanban React IIFE bundle (built second — generates kanban-bundle.gen.ts for server)
  {
    entry: { "kanban-browser": "src/client/kanban/index.tsx" },
    format: ["iife"],
    target: "chrome90",
    platform: "browser",
    outDir: "dist/client",
    clean: false,
    sourcemap: false,
    minify: true,
    noExternal: [/.*/],
    esbuildOptions(options) {
      // Production mode — jsxDev is intentionally disabled to avoid embedding
      // absolute build-machine source paths into the published npm package.
      options.define = { "process.env.NODE_ENV": '"production"' };
      options.outExtension = { ".js": ".js" };
    },
    onSuccess: async () => {
      const bundle = readFileSync("dist/client/kanban-browser.js", "utf-8");
      writeFileSync(
        "src/server/kanban-bundle.gen.ts",
        `// AUTO-GENERATED — run 'npm run build' to regenerate. Do not edit manually.\n/** Production React+Tailwind kanban bundle. Inlined into the HTML shell at build time. */\nexport const KANBAN_BUNDLE = ${JSON.stringify(bundle)};\n`,
      );
      console.log("[tsup] Generated src/server/kanban-bundle.gen.ts");
    },
  },
  // CLI bundle
  {
    entry: ["src/index.ts"],
    format: ["esm"],
    target: "node22",
    outDir: "dist/cli",
    clean: false,
    sourcemap: false,
    minify: true,
    dts: true,
    banner: { js: "#!/usr/bin/env node" },
    esbuildOptions(options) {
      // Inject package version at build time so the CLI can check for updates
      // without reading the filesystem at runtime.
      const pkg = JSON.parse(readFileSync("package.json", "utf-8")) as { version: string };
      options.define = { ...options.define, __VIBEFLOW_CLI_VERSION__: JSON.stringify(pkg.version) };
    },
    onSuccess: async () => {
      // Keep dist/index.js in sync with dist/cli/index.js so that both
      // `node apps/cli/dist/cli/` and `node apps/cli/dist/` resolve the same
      // (up-to-date) binary. Without this, dist/index.js can become a stale
      // artifact that still serves the old kanban template (e.g. with the
      // proto-overlay.js script tag that was removed from the React shell).
      const { copyFileSync, chmodSync, readdirSync: rds } = await import("node:fs");
      copyFileSync("dist/cli/index.js", "dist/index.js");
      try { copyFileSync("dist/cli/index.d.ts", "dist/index.d.ts"); } catch { /* optional */ }
      // Copy chunks so `node dist/` resolves the same modules as `node dist/cli/`
      for (const f of rds("dist/cli/").filter((n: string) => /^(chunk|workspace|files)-/.test(n))) {
        try { copyFileSync(`dist/cli/${f}`, `dist/${f}`); } catch { /* ignore */ }
      }
      // Remove stale sourcemap files (may have been generated by previous dev builds)
      for (const dir of ["dist", "dist/cli"]) {
        try {
          for (const f of rds(dir).filter((n: string) => n.endsWith(".map"))) {
            rmSync(`${dir}/${f}`, { force: true });
          }
        } catch { /* ignore */ }
      }
      chmodSync("dist/index.js", 0o755);
      console.log("[tsup] Synced dist/index.js ← dist/cli/index.js");
    },
  },
]);
